### ISSUE TITLE
[FEATURE REQ] structure of data that needs to be exported as a JSON or CSV 

### ISSUE THREAD

**Issue by MadhavJivrajani** [pesos/grofer#36]
The format in which data needs to be exported needs to be discussed and decided upon. For instance, for overall/general information about the system being exported as a JSON, how will it be exported and to what level should the JSON be nested?

```
{
   cpu: {
        0 : %
        1: %
        ...
   },
   mem: {...}
}
```
or 
```
{
    cpu: [...],
    mem: [...],
}
```

^ just an example of what needs to be discussed and decided upon!

**Comment by anihm136** [comment]
Personally, I'd prefer as little nesting as possible. All stats can be represented by an array, where each index represents the value of the stat at a specific point in time. If required, each array element can be made into an object to give more information if required (an example would be the exact timestamp at which it was recorded). 
Since CSV is one of the formats we plan to export to, and it does not support nesting, we should plan out at least one non-hierarchical way of representing the data. From there, we can think of grouping logically similar elements together if it makes sense (such as CPU cores)

**Comment by MadhavJivrajani** [comment]
Hmm, alright, for JSON, when exported, it will have to be an array of objects, with each object having the time at which data was fetched. For more verbosity/intuition the nesting depth can be increased. 

For CSVs, I was thinking, have each piece of information as a column (including CPUs, each CPU is a different column) and have a column for time that uniquely identifies each row. 

Also "timestamp" should be a Unix epoch IMO because its easier to operate on and can be converted to any unit of time as required by the user.

**Comment by metonymic-smokey** [comment]
@MadhavJivrajani so to be clear, is this what you're saying WRT CSVs:  
Timestamp is the first column, the next 'n' columns are for each CPU core and each record in those columns will be an array storing some values of metrics(in a fixed order) at that time?

**Comment by metonymic-smokey** [comment]
For proc stats for an individual process, we could specify the total interval for which to export and the interval at which to fetch stats, via flags. For example, 2 mins./5 sec. for a specific PID will give 36 timestamped rows with stats for that process, with each stat in a different column.

**Comment by Gituser143** [comment]
I would prefer the nested JSON as @MadhavJivrajani suggested, but this might have it's own issues to deal with. Because Marshalling huge data structures into JSON will be an issue. CSVs on the other hand will be fairly straight forward. Each row having a time stamp followed by stats as columns is perfect to implement.

**Comment by MadhavJivrajani** [comment]
@metonymic-smokey why array? If you have different columns in the CSV then the value corresponding to them can be atomic, right?

**Comment by metonymic-smokey** [comment]
@MadhavJivrajani yeah right, my bad.   
What about proc stats?

**Comment by Gituser143** [comment]
I don't think it makes sense to export data out of `grofer proc`, but for a specific process we can apply the same format of nested JSON/CSV with atomic values. How does that sound?

**Comment by MadhavJivrajani** [comment]
I've added boilerplate code for exporting as JSON, I've hardcoded a lot of configuration options that are to be implemented. 
The code is on the `export` branch ([link](https://github.com/pesos/grofer/tree/export)). Run it once and let me know if the format seems okay to you guys!
